export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const USER_ROLE_CHOSEN = 'USER_ROLE_CHOSEN';
export const USER_ROLE_ERROR = 'USER_ROLE_ERROR';
export const SET_STUDENT_ID = 'SET_STUDENT_ID';
export const SET_COACH_ID = 'SET_COACH_ID';
export const USER_INFO_UPDATE = 'USER_INFO_UPDATE';
export const USER_INFO_UPDATE_FAILED = 'USER_INFO_UPDATE_FAILED';
export const USER_INFO_UPDATE_SUCCESSFUL =
  'USER_INFO_UPDATE_SUCCESSFUL';
export const FECTH_USER = 'FETCH_USER';
export const FECTH_USER_FAILED = 'FETCH_USER_FAILED';
export const FECTH_USER_SUCCESSFULLY = 'FETCH_USER_SUCCESSFULLY';
